### ISSUE TITLE
Checking for model's permissions in reversion's views

### ISSUE THREAD

**Issue by pcraston** [etianen/django-reversion#176]
Can I start off by saying what a brilliant app django-reversion is. Easy to use and so powerful.

However, we noticed an auth bypass issue where a user can view the model's complete change history even if he doesn't have permissions for that model.

Users that don't have (change, add or delete) permissions for a model can view django-reversion's change history page (and in fact all other admin pages) for an app by navigating directly to the to link.

To fix, I could add the following lines to each of the views in admin.py:

``` python
# get ContentType for model to check if user has appropriate permissions
model_content_type = ContentType.objects.get_for_model(self.model)
if not request.user.has_perm('%s.change_%s' %(model_content_type.app_label, model_content_type.name,)):
      return HttpResponseForbidden('Forbidden')
```

But it might make sense to check for the "add" permission for the recoverlist_view instead of always checking for "change" permissions?

Do you have any thoughts on this?

**Comment by gitanupam** [comment]
I want to show the change history to users who don't have permission to change the object i.e they can look at all the changes that happened but can't change the object themselves - is that possible to do with the current version of the django-reversion?

echo: brilliant library indeed!

**Comment by etianen** [comment]
A good question. I've not actually used Django's admin system in a long
while, so you'll have to remind me of it's behaviour.

I understand that Django has a "view" as well as a "change" permission now?
And if you only have "view" permission then the Django admin detail view
for a model is read-only?

If so, this should be how django-reversion works too. And I believe it
doesn't right now.

**Comment by gitanupam** [comment]
Actually we are using v1.10 which has three permissions: add/change/delete. If none of these permissions are set for the user (but the user is_active and is_staff), they got a 403 forbidden when they access the history link

**Comment by etianen** [comment]
I'm confused. I thought a user without add/change/delete permissions could
not even view the model?

**Comment by gitanupam** [comment]
You are right (and I verified that by creating a test user with is_staff but no add/change/delete permissions).

We have a detail template for each object on the (non-admin) front-end of the app where the user can view the model object. So even if the user does not have the above permissions on django admin they can still view the model on the front-end of the app. On each template page, there is also a history button where we want them to see the change history of that object. This history button links to reversion's history link on the django admin. I am ok to provide all the users with is_staff so their login to django admin works but did not want to give them edit access to the model objects.

But I think you are right - since this is piggy backed on django-admin, we can't just show the history to users who dont have view access on django admin.

I guess I'll have to figure a way out to get this history as well on the front-end template so we don't have to deal with permissions on django admin.

**Comment by etianen** [comment]
It's not hard to adapt the Django admin, or indeed write a new view using
the django-reversion low-level API to do what you want. That seems a good
approach, like you say.

Interestingly, I've taken the same permissions approach in the app that
makes up my day job. All staff users can view everything, but
add/change/delete perms are respected. Otherwise there's a massively
complex set of logic required when you have multiple interrelated models in
a view.
