### ISSUE TITLE
revert should delete existing objects not present in the version

### ISSUE THREAD

**Issue by abrahammartin** [etianen/django-reversion#371]
I have a model A and a model B. The model B contains a ForeignKey to model A. I register with reversion both models:

```
class A(models.Model):
    pass

class B(models.Model):
   a = models.ForeignKey(A)

reversion.register(A)
reversion.register(B, follow=["a"])
```

If I create an object a1, reversion will create a new version containing a1. If I later create an object b1 with b1.a = a1, it will create a new version containing b1 and a1 (because of the follow parameter in reversion.register). If I later create a second object b2, with also b2.a = a1, I'll have a third version containing a1, b1, and b2. If I want to restore the second version now, ideally, b2 should be deleted, because, again, of the follow parameter. Does this make sense? Is there any reason why reversion should not do that?

**Comment by nlj24** [comment]
Hello, to follow up on this... Where do I set that option? Do I go into the reversion library code? All I did was subclass my model admins as described, so do I need to set up the revision system on a lower level to set delete=True?

**Comment by etianen** [comment]
Are you using the VersionAdmin integration? If so, you don’t need the reversion.register code at all. The VersionAdmin should auto-register the models for you, and the nested deletes should work as you expect.

**Comment by nlj24** [comment]
Yes instead of admin.modelAdmin I am subclassing from reversion.VersionAdmin. I tried this again today with the basic django tutorial polls app to make sure there were no confounding variables and I did the following: after running sync db and createinitialrevisions, I added a new choice to my Question model (as per the Django tutorial polls app). Then, I went to history and clicked on the initial version, which had one fewer choice. On this page, the checkbox for that new choice I had added was checked, which is good since if I want to revert back that new choice should be deleted. However, when I click save, with the checkbox for delete checked, that choice is not deleted.

Any thoughts on why that may be? Thanks for the quick responses!

**Comment by etianen** [comment]
That sounds like a bug. I’m afraid I don’t have the time to look into it for the time being, as it’s one of the gnarly parts of django-reversion, but when I’ve got some spare time, I’ll pick this up again.

I’ll alternatively take a pull request from a brave developer, willing to dive into the hacky admin integration.
