### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_authenticated'

### ISSUE THREAD

**Issue by gdonald** [etianen/django-reversion#383]
I upgraded to Django 1.7.4 and Reversion 1.8.5.

If a user provides the wrong password on login I get the error:

File "/usr/local/lib/python2.7/dist-packages/Django-1.7.4-py2.7.egg/django/core/handlers/base.py", line 204, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python2.7/dist-packages/reversion/middleware.py", line 34, in process_response
    and hasattr(request, "user") and request.user.is_authenticated() \
AttributeError: 'NoneType' object has no attribute 'is_authenticated'

It works fine if the user provides the correct login password but that won't always be the case.

**Comment by etianen** [comment]
I've just uploaded a fix to master. Please confirm that this fixes the issue.

It's actually not recommended to use RevisionMiddleware, ever since Django deprecated TransactionMiddleware.

Check out the warning here: http://django-reversion.readthedocs.org/en/latest/api.html#revisionmiddleware

There's a discussion with the Django devs going on here:

https://groups.google.com/forum/#!topic/django-developers/uW5Ogio8QBc
