### ISSUE TITLE
Workaround for "separate database transaction since Django 1.6"

### ISSUE THREAD

**Issue by guettli** [etianen/django-reversion#392]
I refer to this:

http://django-reversion.readthedocs.org/en/latest/api.html#revisionmiddleware

{{{
Warning: Due to changes in the Django 1.6 transaction handling, revision data will be saved in a separate database transaction to the one used to save your models, even if you set ATOMIC_REQUESTS = True. If you need to ensure that your models and revisions are saved in the save transaction, please use the reversion.create_revision() context manager or decorator in combination with transaction.atomic().
}}}

There is an easy work around, which is not obvious:

set ATOMIC_REQUESTS to False and create an own Middleware which starts a transaction for every request.

Related: https://groups.google.com/d/msg/django-users/njeVp4zT5HA/9g0wsFYZKAwJ

I think one of these things should be done now:

 - document the work around 

 - Provide a Middleware which starts a transaction for every request.

What do you think?

**Comment by etianen** [comment]
The django revision middleware was deprecated because Django middleware does not actually guarantee to bracket a request with a start and end transaction. Implementing our own transaction middleware is just re-implementing a deprecated feature that was deprecated for a good reason.

I believe that the Django devs are aware of the issue of having no easy way to wrap the entire request in a database transaction, but no solution has yet to present itself.
