### ISSUE TITLE
1.8.3 broke compatibility on a minor version change

### ISSUE THREAD

**Issue by andybak** [etianen/django-reversion#398]
I would normally expect to be able to put something like this in my requirements.py:

    django-reversion>=1.8,<1.9

but 1.8.3 broke compatibility with Django 1.6. Shouldn't that have been cause for a major version bump?

Alternatively - is there a strong reason to break compatibility? The generics import error should be easy to patch for <1.7. Are there more complex issues?

**Comment by etianen** [comment]
I don’t know… Django occasionally puts out breaking changes in a minor version update, so it’s not inviolable. I tend to see a bump in the major version number being for changes to the django-reversion API, rather than it’s dependencies.

BUT, I can see how that would cause annoyance. In future, I’ll bump the major version number when breaking compatibility with previous Django versions.

There’s no real reason to not support Django 1.6 at this time. It’s normally changes to the django admin that breaks things. I’ll see if I can fix support for Django 1.6, and push out a new version today.

**Comment by etianen** [comment]
Okay, the latest master branch should support Django 1.6. Let me know if it works for you.

**Comment by andybak** [comment]
Yep. Seems good so far.

**Comment by etianen** [comment]
1.8.7 has landed!
