### ISSUE TITLE
Reversion not working on Celery or Shell 

### ISSUE THREAD

**Issue by MounirMesselmeni** [etianen/django-reversion#404]
Reversion is not working on Shell or Celery, after debugging I found that the admin files are called, the signals are there but the Reversion Context is deactivated and that's why it's not working.
I had to implement this code to be able to use Reversion on Celery:

```python
def task_pre_run_handler(**kwargs):
    """Activate Reversion Context Manager"""
    reversion.revision_context_manager.start()


def task_post_run_handler(**kwargs):
    """Deactivate Reversion Context Manager"""
    reversion.revision_context_manager.end()


task_prerun.connect(task_pre_run_handler)
task_postrun.connect(task_post_run_handler)
```

**Comment by etianen** [comment]
This behaviour is documented here:

http://django-reversion.readthedocs.org/en/latest/api.html#creating-revisions

Rather than using reversion.revision_context_manager.start() and reversion.revision_context_manager.end(), consider decorating your tasks with reversion.create_revision(), or using the reversion.create_revision() context manager.
