### ISSUE TITLE
Really slow on large datasets

### ISSUE THREAD

**Issue by psychok7** [etianen/django-reversion#439]
Hi there, so i am trying out `django-reversion==1.8.7` + `django 1.7` in my admin on a table that has about 300.000 records and its really slow when i click on `recover deleted` which i am assuming it will call `get_deleted` method.

I am using it on my development machine (vagrant) with 1 core and 4 GB RAM. Is there anything i can do to make this work? Is this supposed to work well for these many datasets?

Thanks

**Comment by psychok7** [comment]
This issue seems to be a duplicate of this one https://github.com/etianen/django-reversion/issues/368

**Comment by etianen** [comment]
Does your model have an integer primary key? Without that, reversion runs
kinda slow.

Try running get_deleted() in a python terminal and see if it's still slow.
That'll help pinpoint the issue.

**Comment by psychok7** [comment]
@etianen yes i have an integer primary key. I also tried it in the terminal and it is also very slow, couldn't even wait that long for the results.

any ideas??

**Comment by etianen** [comment]
You could try the code you linked to in your mailing list email? They claim
it made things faster. If so, then it could be included in reversion core
(although I suspect it'll eat RAM like crazy).

**Comment by psychok7** [comment]
@etianen you means this one?

```
def get_deleted(self, model_class, select_related=None): 
        """ 
        Returns all the deleted versions for the given model class. 

        You can specify a tuple of related fields to fetch using the 
        `select_related` argument. 
        """ 
        content_type = ContentType.objects.get_for_model(model_class) 
        deleted = [] 
        # HACK: This join can't be done in the database, due to 
incompatibilities 
        # between unicode object_ids and integer pks on strict 
backends like postgres. 

        not_deleted = {} 

        for not_deleted_item in model_class._default_manager.all(): 
            not_deleted[str(not_deleted_item.id)] = True 

        for object_id in 
self.filter(content_type=content_type).values_list("object_id", 
flat=True).distinct().iterator(): 
            if object_id not in not_deleted: 
                deleted.append(self.get_deleted_object(model_class, 
object_id, select_related)) 
        deleted.sort(lambda a, b: cmp(a.revision.date_created, 
b.revision.date_created)) 
        return deleted 
```

ok i will have a go and give you a feedback

**Comment by psychok7** [comment]
@etianen i copied to above code to the source and when i try calling the get_deleted function i get a `AttributeError: 'RevisionManager' object has no attribute 'filter'` . any ideas?

**Comment by etianen** [comment]
Looks like that method is supposed to belong on the version model manager.

**Comment by alexey-v-paramonov** [comment]
The problem is in VersionQuerySet.get_deleted method. It generates a very slow query to get deleted items, and the slowest part of it is (I will keep the names of my tables):

```SELECT MAX(V0."id") AS "latest_pk" FROM "reversion_version" V0 WHERE (V0."db" = 'default' AND V0."content_type_id" = 216 AND NOT (V0."object_id" IN (SELECT CAST(U0."id" as text) AS "id_str" FROM "podblogs_post" U0))) GROUP BY V0."object_id"```

This query has a sub-query to get a list of items that are in `reversion_version` table but not in `podblogs_post`. I have about 200.000 records in my tables so this query runs almost 40 minutes on my Core i7 laptop. 
But getting a list of delete items is much more simple with JOIN:

```SELECT MAX(V."id") AS "latest_pk" FROM "reversion_version" V 
LEFT JOIN "podblogs_post" P ON CAST(V."object_id" AS INT)=P."id" WHERE V.db='default' AND V."content_type_id"=216 AND P."id" IS NULL GROUP BY V."object_id";
 ```
This query returns the same results as the one above and runs 300 ms only compared to 40 minutes.
So in my project I decided to override `recoverlist_view` method and replace `get_deleted` method with a raw SQL query:

```
        deleted = Version.objects.raw(
        '''
        SELECT * FROM "reversion_version"
        WHERE (
           "reversion_version"."db" = '{1}' AND "reversion_version"."content_type_id" = {0} AND "reversion_version"."id" IN (
              SELECT MAX(V."id") AS "latest_pk" FROM "reversion_version" V
              LEFT JOIN "podblogs_post" P ON CAST(V."object_id" AS INT)=P."id" WHERE V.db='{1}' AND V."content_type_id"={0} AND P."id" IS NULL GROUP BY V."object_id"
            )
        )
        ORDER BY "reversion_version"."id" ASC
        '''.format(content_type.id, Version.objects.db)
        )
```
Now `Recover deleted posts` page opens instantly. You can apply similar query to your model admin.

**Comment by etianen** [comment]
Thanks for the detailed report!

I've just pushed an optimization to master that uses your JOIN for `get_deleted()`. Would you mind checking it out and seeing if it works as fast as your `recoverlist_view` hack?

**Comment by alexey-v-paramonov** [comment]
Works blazing fast now, checked and confirmed.

**Comment by etianen** [comment]
Wow, that's excellent!

That query has been slow for the entire history of django-reversion, and I
couldn't think of any way to improve it. You've done the world a fine
service! :D

**Comment by jamesmalone** [comment]
This is great and critical fix - will you be releasing this as an official 'release' any time soon?
Thanks,
JM

**Comment by etianen** [comment]
I'm fighting deadlines at the moment, but a reversion release can be done
next week.

**Comment by etianen** [comment]
v2.0.11 will be out in about 10 mins, once Travis has finished the build.

**Comment by passuf** [comment]
I've had the same problem on an Oracle database with ~300k records and the `recover deleted` button would load for more than 30 minutes without a result. 

The faster query introduced with v2.0.11 only needs to be adjusted slightly in order to support Oracle databases, see pull request #691. Basically, the `AS` in the `FROM` clause needs to be removed, since this is illegal on Oracle but optional on SQLite or PostgreSQL (see [this StackOverflow answer](https://stackoverflow.com/a/21145075)).

Using the faster query, the request now takes about 1 second to complete.

Please let me know if I can do any other testing using an Oracle database.

**Comment by etianen** [comment]
Thanks for the pull request, and let me know if your Oracle adventures find
anything else. I don't have access to an Oracle server, so testing is
impossible for me.
