### ISSUE TITLE
Empty user (and comments) field for revisions created outside admin

### ISSUE THREAD

**Issue by SaeX** [etianen/django-reversion#461]
I'm using the `'reversion.middleware.RevisionMiddleware'` middleware setting along with `reversion.register(MyModel)` after every model definition.
All my models have a `created_by` and `updated_by` field.

For objects that are updated through the Django Admin, I get a User and Comments field that is properly filled in.
However, for objects that are created or updated through my own non-admin views, the revision is created (done by the middleware) but there is no User or Comment information. I'm especially interested in the User part.
When having a look at the revisions in the admin, a dash (`-`) is displayed in the User and Comments column for those non-admin created/modified objects.

Any idea on what the proper way is to get proper tracking who changed the object, outside the admin?

Note that the `created_by` and `modified_by` fields seem to be tracked by reversion:

	'_field_dict_cache': 
	{
	'modified_by': None, 
	'title': u'test', 
	'created': datetime.datetime(2015, 11, 11, 10, 30, 24, 682000, tzinfo=<UTC>), 
	'modified': datetime.datetime(2015, 11, 11, 11, 1, 20, 515000, tzinfo=<UTC>), 
	'created_by': 1, 
	u'id': 1, 
	}, 

Thanks!

**Comment by etianen** [comment]
If you want comments on the revisions, then you'll have to call
reversion.set_comment() somewhere in your view. There's no functionality to
generate change comments outside the admin, since the admin functionality
directly piggybacks off the admin's own message generation functionality.

The RevisionMiddleware should add the user in for you automatically. So
long as you're accessing request.user somewhere in your view,
django-reversion should pick up on this automatically.

**Comment by SaeX** [comment]
Hmm, so there should be no need to do anything manual when using `RevisionMiddleware`, right?

Request.user can be accessed (but I'm not calling this explicitly). 

Can you please point out what I'm doing wrong? I created a test project for reproducing the issue.
https://github.com/SaeX/django-reversion-issue-461/

I get a "-" in the User column with the Model History, even when I'm logged in when changing an object.

See the below image: 

![Image of issue 461](http://i.imgur.com/2IFdGHF.png)

**Comment by etianen** [comment]
You have to explicitly access request.user somewhere in your request for
the revision middleware to pick it up. Normally, this is done by the
templates with a "you are logged in as" message.

**Comment by SaeX** [comment]
Thanks for your comments, etianen. I've updated the example project on https://github.com/SaeX/django-reversion-issue-461/. The project was changed to show `request.user` in my edit view (through newly added `'django.core.context_processors.request'` and to show `self.request.user` through an `UpdateView`.

While I do get my logged in username (using both methods), the issue persists: the User column remains as "-" in the admin view.

Anything else I might be doing wrong?

**Comment by etianen** [comment]
I'd put some logging lines into the revision middleware, here:

https://github.com/etianen/django-reversion/blob/master/src/reversion/middleware.py#L33

With a few print statements, you can find out which of the conditions for
the user being added are not being met.

**Comment by SaeX** [comment]
Thanks for the suggestion. I've added some logging lines:

	hasattr(request, 'session'): True
	request.session.accessed: False
	hasattr(request, 'user'): True
	request.user is not None: True
	request.user.is_authenticated(): True
	revision_context_manager.is_active(): True

Everything yields True, except for `request.session.accessed`. What does this do exactly? And why is it needed?
I'm not really (or really not) familiar with writing Middlewares. I found that request is a `HttpRequest`, and request.session hence is https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.session, using `SessionMiddleware` as per https://docs.djangoproject.com/en/1.8/topics/http/sessions/. But no sign of `accessed` there.

**Comment by etianen** [comment]
In Django, the act of accessing the session marks the whole view as being
"per user", which adds a Vary: Cookie header onto the response. This has
the effect of effectively preventing the page being cached, so that
different users see different versions of the page.

Thus, reversion will only mark a revision with the current user if some
other part of your app has already accessed the session. Otherwise, the
effect of adding RevisionMiddleware would be to make your entire site
uncacheable, which is rarely what's desired.

If session.accessed is False, then your view isn't actually accessing
request.user anywhere. A simple call of `request.user.username` somewhere
should trigger it.

Alternatively, you could just create a modified version of
RevisionMiddleware that doesn't perform this check. However, it will break
caching across your entire site!

TBH, the RevisionMiddleware is not a recommend approach any more. You
really want to wrap all revisions in a transaction, which is impossible
using the RevisionMIddleware ever since Django dropped support for
TransactionMiddleware.

**Comment by slashme** [comment]
I'm having exactly this problem, and I'm also using class-based views. None of the information that I can find explains how to wrap revisions in transactions with class-based views.

In models.py I have something like:

```
class Layer(models.Model)
    def get_absolute_url(self):
        return "/layer/%i/" % self.id
    name = models.CharField(max_length=10)
    #etc.

reversion.register(Layer)

class LayerAdmin(VersionAdmin):
    pass

admin.site.register(Layer, LayerAdmin)

class LayerForm(ModelForm):
    class Meta:
        model = Layer
        fields = ['name', 'description', 'website', 'color']
```

and in views.py:

```
class LayerUpdate(UpdateView):
    model = Layer
    form_class = LayerForm
```

What is the "right" way to get user information saved with revisions?

Thanks,

David

**Comment by etianen** [comment]
You could create a class mixin to handle this for you:

``` python
from reversion import revisions as reversion

class RevisionMixin(object):

    @reversion.create_revision()
    def dispatch(self, request, *args, **kwargs):
        if request.method in ("GET", "POST", "PATCH", "PUT") and request.user.is_authenticated():
            reversion.set_user(user)
        return super(RevisionMixin, self).dispatch(request, *args, **kwargs)
```

Then mix it in like:

``` py
class LayerUpdate(RevisionMixin, UpdateView):
    model = Layer
    form_class = LayerForm
```

**Comment by etianen** [comment]
If there's interest in this functionality, I could include an official RevisionMixin in the next release of reversion. I'd also cover RevisionMiddleware in deprecation warnings, as it's really not a good idea to do!

**Comment by slashme** [comment]
Thank you, that is very clear! I'll try it out this evening.

**Comment by slashme** [comment]
Yay, it works!  One minor correction: 

``            reversion.set_user(request.user)``

Thank you so much.

**Comment by etianen** [comment]
Thanks, I've corrected the original example. I've also corrected the list of HTTP headers. It should be POST, PUT, PATCH.

(This is because accessing request.user in the view will add a Vary: Cookie header, breaking most caching. You don't want that on every GET request. However, almost all POST, PUT and PATCH requests won't want caching anyway, so it's a decent metric to use.)

**Comment by mcastle** [comment]
Works for me, too.
