### ISSUE TITLE
Problem with proxy models and inlines

### ISSUE THREAD

**Issue by RamezIssac** [etianen/django-reversion#465]
Use case: model and a sub model, both are proxies, created and edited via admin using inline,
Problem: The history view show only changes done to the parent model.
in other terms:
Recorded changes for proxy models within inlines are not visible on the history view

During investigation, i noticed in the version table, changes recorded foreignkey content_type to concrete model.  (changes in parent proxy are recorded pointing to concrete model, same with the child model)
while in django_admin_log -as example- ,  changes (in parent or child) are recorded pointing to the parent proxy model, which makes it easier to retrieve.

How can i go about solving the Problem? any hints where to start ?

**Comment by RamezIssac** [comment]
Well well, i couldn't reproduce it in reversion tests ... :-)

Could you elaborate on how the versions get collected for the history view,like a guide to reversion internals if you may 

Thanks.

**Comment by etianen** [comment]
The versions are collected by following a reverse foreign key, which is set up in the `follow` argument of `register`.

So, if you call `register(YourModel, follow=("something_set",))`, then whatever is returned by following that model property is used to populate the inlines.

**Comment by etianen** [comment]
I've just updated the tests to use a proxy parent and a proxy child model. Still can't reproduce, I'm afraid.

**Comment by RamezIssac** [comment]
I confirm, issue not reproduced. That's interesting :)
Will give my project some debugging to know where the deviation came from and get back to you.

Grateful for your help and patience

**Comment by etianen** [comment]
No worries! I'd be very interested to track this down.

The latest django-reversion uses database transactions to roll back
revisions for preview, which should make it work with extremely esoteric
examples of proxy models. I'd be very interested if there is a way to break
it!

**Comment by RamezIssac** [comment]
GOT IT !!
The issue appear when the Base Models (not proxy) are not used on their own , so an error page appear suggesting to register (once for the inline first, then for the parent), so i do and register them explicitly,
and UNLESS the parent base model is registered using the follow=['children'], the issue will appear.

And that's also the only difference between your added test, and the PR #471 

Phewwww :-)

**Comment by etianen** [comment]
So you just need to update your register code, and it works?

Phew! :D

**Comment by etianen** [comment]
Anyway, thanks for taking the time to put together actual test cases to
help debug the issue. If only all issues were like that... :P

**Comment by RamezIssac** [comment]
Well.... 
What do you think ? 
Shouldn't the automatic registration handle such case and follow what the actual inlines says (as long as base models are registered) ? 
If not, then a note about it in the docs would be great.

And Yes, in fact all it took in this case is to add follow children on the base model registration, but there was noway for me to know that. 

And i deeply thank you for your time, support and patience and this wonderful piece of code :-)

**Comment by etianen** [comment]
The explicit registration overrides the automatic admin registration. It's
a feature, not a bug! :P

I'll put a note in the admin docs about it.

**Comment by RamezIssac** [comment]
Lol :)
what i'm saying is that the explicit registration is for the base model and the admin registration is for the proxy model, shouldn't there be some room here for them not to override each other ?

And as the docs note,  in a similar case we need to explicitly follow any children , proxy children and generic children. Right ?
And "similar case" definition would mean: "a Proxy parent whom base is not admin registered but explicitly registered", would you agree?

**Comment by etianen** [comment]
This makes my head hurt!

I'll have a review of the proxy support next week, as it was contributed by
someone else, and I can't quite remember what we agreed.

Instinctively, I think reversion should treat proxy modes and concrete
models as the same model, since the backing data is the same, and reversion
only cares about the backing data.

**Comment by RamezIssac** [comment]
I want to share with you some thoughts.
1. When saving a revision of a proxy model, the reversion.contenttype id points to the proxy model and not to the base. and that's good because, 
2. One of the main uses of proxy model is having a different admin screen with a different set of inlines and of user permissions. 
3. Consider this case where I create a proxy model to specify a GenericRelation, and i would want to follow using reversion, which seem tricky to do in the current implementation.
4. It gets trickier when proxy model is in a different app then the base model.

Finally, In the light of point 1, my gut feeling says that's a "not a major" tweak to allow proxy model to follow stuff that isn't set explicitly when registered the base model.

I'll go around the code and get back.

**Comment by etianen** [comment]
So, as far as I can tell, django-reversion allows different registration
options for proxy models versus their concrete models. Probably.

However, the codebase uses ContentType.objects.get_for_model()  to get the
content type for the proxy model, which means that when saving or looking
up versions, versions for both concrete and proxy models are returned,
since all share the same content type ID.

So you can:
1. Register with different options for proxy models
2. Have those options honoured when saving a proxy model
3. BUT - When loading versions, you'll get back data for all models.

This seems inconsistent and wrong. I think that django-reversion should use
for_concrete_model=False when calling ContentType.objects.get_for_model().
That way, the proxy models are treated exactly as a user would expect, as a
different model.

However, changing this behaviour might cause some surprises to existing
users.

**Comment by RamezIssac** [comment]
i'm still looking this up, but allow me to disagree with you on couple of points:

1. "since all (proxy and non-proxy) share the same content type ID" No, they don't , and the codebase actually save them with their accurate contenttype_id.
2. Registering with different options for proxy doesn't work. (Explicitly or via admin)

As far as i went i can say, the problem might be when getting the follow option while saving, codebase looks for the concrete model option instead of the proxy.

**Comment by etianen** [comment]
Really? How does it save different content types for different proxy
models. It uses ContentType.objects.get_for_model() without the
for_concrete_model=False option.

**Comment by RamezIssac** [comment]
Will revise...

**Comment by RamezIssac** [comment]
I'm extremely sorry, i got that mixed up! You're right.
You're right also about changing the behavior affecting existing users.. and it will also break the creatinitalreversions command.

So, how about this:
When saving the reversion we use the proxy contenttype id (the right thing to do)
But, when getting the reversion we search by both proxy and concrete, (using ``__in`` or ``or`` operators) ?
Reasonable idea ?!

**Comment by RamezIssac** [comment]
demonstrated in PR #475 

Thanks.

**Comment by etianen** [comment]
I'm not sure that will produce desired behaviour. Some nasty side effects
would include:

1. When running createinitialrevisions, initial revisions will be created
for the concrete model and all proxy models.
2. The admin history page, plus the get_for_object() method, will then
return all revisions for all concrete and proxy models.

Your proposed change would still have the same behaviour as currently, in
that proxy models would permit separate reversion configuration, but the
Version lookup methods would return versions across all proxy and concrete
models. It's just the database representation that would change.

Our options for registration behaviour can be one of:
1. Permit different configuration for proxy models.
2. Treat concrete and proxy models as same model when registering.

Our options for version storage and retrieval can be one of:
1. Permit different version histories for concrete and proxy models.
2. Treat version history for proxy and concrete models independently.

Taken together, the only sane options are (1) and (1), or (2) and (2).
Currently we have (1) and (2), which is inconsistent.

I'm increasingly of the opinion that the correct approach is (2) and (2).
This is because reversion only concerns itself with data, and the proxy
models are backed by the same data.

**Comment by RamezIssac** [comment]
Can't we try to skip those nasty side effects ? I think, side effect 1. is not a that big of a problem, or at least it can be handled gracefully after deciding the best approach.

I also think that (2) and (2) is not the best, because data -in the big sense- contains what we follow and the user permissions and that's disregarded in 2,2 path.

#475 purpose is to try and solve the issue in a back-ward compatible way.. we can of course drop it for another path
How about to try and create/update reversions saved in the "old" format, so existing users are safe ?

**Comment by etianen** [comment]
I don't think it's possible to solve this in a backwards compatible way. At
the moment, the behaviour is inconsistent, because the current behaviour is
(1) and (2).

Whether (1) and (1), or (2) and (2) is chosen, behaviour will break.

**Comment by RamezIssac** [comment]
Working at recreating revisions for proxy models won't help ?! via a management command something like `update_proxy_reversions` maybe ?
It's tricky of course and would need lot of tests. We can work on that if you agree with the path.
it can be In a new release with a clear warning to users to run this command.
Maybe with an option to keep  the old behavior going on too.

What do you think ?

**Comment by etianen** [comment]
I like the idea of an option to allow the user to choose behaviour. We can
take a similar approach to Django.

reversion.register(YourModel, for_concrete_model=True)

The for_concrete_model option defaults to True. If true, then the content
type of Revisions will be set to that of the concrete model. If set to
False, then the content type will be set to that of the Proxy model.

In either case, both proxy and concrete models can be registered with
different options.

The change is backwards compatible because the default option is the
current behaviour.

If the user leaves the for_concrete_model option as False, and registers
proxy and concrete models with the same options, then you get behaviour (1)
(1). If they set for_concrete_model as True, and register proxy and
concrete models with different options, they get behaviour (2) (2).

**Comment by RamezIssac** [comment]
Very Cool, A tiny detail left, the admin "implicit" registration .
Add an admin option reversion_for_concrete_model maybe ?!

**Comment by etianen** [comment]
Yes, perfect. :)

**Comment by RamezIssac** [comment]
:)  One more idea:
we can make the behavior also controllable -project wide- via an option,
along side with the per model registration.

I'm very happy we reached this point.
Great work man !!

Shall I work on a PR for this?

**Comment by etianen** [comment]
I'd rather not have a global django setting, since django-reversion doesn't
have any of these so far. Also, it could break third-party apps. I think
making register() the sole source of truth is safer.

**Comment by etianen** [comment]
This has been implemented in the refactor branch:

https://github.com/etianen/django-reversion/tree/refactor

Set for_concrete_model=False when registering models with reversion.
