### ISSUE TITLE
Setting timestamp on a new revision

### ISSUE THREAD

**Issue by invliD** [etianen/django-reversion#482]
Please add an API for setting the timestamp of a new revision. It's also impossible to modify the timestamp of an existing revision as a workaround, because of the use of `auto_now_add`.

The reason I'm asking for this feature is a script I'm writing to migrate a lot of data from our old CMS to our new Django app. The old CMS also had revision support, so I'd like to keep the revisions including timestamp, but I cannot currently set it using reversion.

**Comment by etianen** [comment]
You can just create Version and Revision models manually, I think, or
modify the records that are just created using standard Django ORM.

**Comment by invliD** [comment]
Unfortunately, that's impossible. The Revision model contains the following definition: `date_created = models.DateTimeField(auto_now_add=True, …)`. `auto_new_add` prevents any modification of that attribute (see [Django docs](https://docs.djangoproject.com/es/1.9/ref/models/fields/#django.db.models.DateField.auto_now_add): "Note that the current date is _always_ used; it’s not just a default value that you can override.")

**Comment by etianen** [comment]
Oh, yeah. I've hit that before.

A workaround is to follow up every revision.save() with a
Revision.objects.filter(id=revision.id).update(date_created=your_timestamp)

It's two queries per insert, but it works.

Otherwise, I guess a migration could be added to reversion that removes the
auto_now_add in place of default=timezone.now
