### ISSUE TITLE
GET request of revision_form.html templates calls model.save()

### ISSUE THREAD

**Issue by kmahelona** [etianen/django-reversion#568]
I use django signals for running tasks after a model save. It appears that viewing the history of a reversion via "admin/app/model/pk/history/rev#" causes a model.save() to occur. I believe the save is being called in `version.revision.revert(delete=True)` under `_safe_revert(version)` which calls `version.revert()` which calls `.save()`

I'm running tasks that compare the latest revision with the previous one. When I access the admin history view, a post_save signal is called which causes my tasks to run. The logic I use is,
`
if current_version.field_dict['key'] != previous_version.field_dict['key']:
  do_something().
`

This fine for most models.save() because I've either changed the value of the model attribute or both versions share the same value; however, when revision_form.html is rendered no actual model saves are committed and stored in the database, so the logic fails (or rather, it is executed again).

I could rewrite my code to work around this, but I am curious why would `model.save()` be executed in a GET view?

**Comment by etianen** [comment]
In order to properly support foreign keys and other relations in the
revision form template, the model is loaded from the revision database and
saved back into the database. At the end of the view, the database
transaction is rolled back.

This requires that the model's save() method is called, which
correspondingly calls any post_save signals. If any of the post_save
signals have side-effects that take place outside the database, they will
persist outside of the revision preview.

This behaviour is definitely awkward. Solutions and discussion to work
around it would be appreciated!
