### ISSUE TITLE
Change message does not contain info about changes when editing last revision

### ISSUE THREAD

**Issue by arogachev** [etianen/django-reversion#584]
If some fields were changed during editing last revision, the changes are saved correctly, however the change message contains info only about recovering (I enabled translations to my language, but it says something like "Recovered to previous version, saved at (time).").

**Comment by etianen** [comment]
When restoring a revision, the change message is always "reverted to...".
This is because the django admin normally generates the change message, and
this change message generation isn't something that can be hooked into.
Short of re-implementing the entire admin change message functionality in
reversion, there's not a lot that can be done here.
