### ISSUE TITLE
Changes history for specific field of model

### ISSUE THREAD

**Issue by arogachev** [etianen/django-reversion#586]
I think it would be useful feature. Similar to Github, when you can view all commits history and history of specific file.

**Comment by etianen** [comment]
Unfortunately, that sort of functionality is almost impossible to do,
because the serialized model data is stored in serialized text field in the
database. There's no way to make introspecting that data remotely fast.

Well, there sort of is. If the serialization format was forced to
JSON-only, then in postgres it would be possible to use an indexed jsonb
field to make this sort of thing somewhat fast, but this functionality
would be postgres-only.
