### ISSUE TITLE
Unknown microseconds in reversion

### ISSUE THREAD

**Issue by omago** [etianen/django-reversion#599]
Hi,

I have a problem. I notice reversion does something strange. 

I have a datefield called date_activated and in reversion 1 is: 2016-11-07 13:32:03.491000+00:00
Then in second reversion is value becomes: 2016-11-07 13:32:03+00:00

This is very weird because i did not change its value. Where did those microseconds go?

**Comment by etianen** [comment]
That is very odd. Django serializes timestamps as ISO 8601 date strings,
which includes microsecond values.

The bug is almost certainly either in Django's serialization framework, or
your own code. Something, somewhere, discarded those microseconds between
saving revisions. django-reversion just trusts Django's serializers to do
the right thing.
