### ISSUE TITLE
[feature request] custom comments in django admin (e.g. within save_form())

### ISSUE THREAD

**Issue by AndreCimander** [etianen/django-reversion#607]
First of all: thank you for creating and maintaining such a nice OS package! :+1: 

I recently stumbled over setting custom version comments from within the django admin after migrating some admin actions into the ModelAdmin(/AdminForm). Since the django admin creates a "changed elements" message and calls log_change, custom comments from precursor methods like save_form() get overwritten.

I've come up with a quick workaround, but something nicer/more robust would be neat, especially a request-based custom comment that avoids the possibility of overwriting a concurrent save() on the same model admin instance.

```
class VersionCommentAdmin(VersionAdmin):
    """ modified VersionAdmin to allow reversion comments from within admin actions (e.g. save_form()) """

    custom_save_message = None

    def log_addition(self, request, object, change_message=None):
        # fixme: this is not thread safe, concurrent requests may overwrite comments...
        if self.custom_save_message:
            change_message = self.custom_save_message
            self.custom_save_message = None
        super(VersionCommentAdmin, self).log_addition(request, object, change_message=change_message)

    def log_change(self, request, object, message):
        # fixme: this is not thread safe, concurrent requests may overwrite comments...
        if self.custom_save_message:
            message = self.custom_save_message
            self.custom_save_message = None
        super(VersionCommentAdmin, self).log_change(request, object, message=message)

```

**Comment by etianen** [comment]
So you want to set the change message in save_form()?

I think that this would need support from django admin itself, since
django-reversion just re-uses the infrastructure that's already in place.
Unless I'm missing something?

You could make your hack thread-safe by using threading.local. It's still
not ideal, but it'll avoid the race condition.

**Comment by AndreCimander** [comment]
yup, that's exactly what I want to do. We moved some admin actions from external action functions into the ModelAdmin and admin form to allow easier/safer ways to manipulate models (one of our cases: granting a demo to a subscription model).

It might be a handy feature in such cases. I could write a little patch over the holidays if you're interested :)

**Comment by etianen** [comment]
This still feels like a django admin feature, rather than a reversion
feature. reversion just uses the existing django admin change message
functionality.

However, I think I have a solution for you. Override log_change and
log_addition in your admin class, and make then no-ops. Then, just use
reversion.set_comment() in your actions to set the revision comment in a
thread-safe manner!
