### ISSUE TITLE
Security/Integrity of using revert/rollback trick in front-facing views?

### ISSUE THREAD

**Issue by tlambert03** [etianen/django-reversion#694]
Thank you for the awesome app, and please forgive this "non-bug" post on your issue tracker:
I have a front-facing view (based on `reversion.admin.VersionAdmin._reversion_revisionform_view`) that lets users see a previous version of an object (and all its relations) by adding a `?rev=` GET parameter to the URL (my code is below).  It works great, but being relatively new to database management I have a few questions:

1.  When my view is executed, debug-toolbar reports about 10ms between the first `UPDATE` event and the final `ROLLBACK TO SAVEPOINT` event.  I know it's very unlikely with low-traffic websites, but if a second user were to request the page in those 10 ms, am I correct in thinking that they would get the rolled-back version without having explicitly asked for it?
2. It seems safe enough for an admin view, but from the viewpoint of database integrity, is it risky to have a public-facing view that lets users "abuse" the revert/rollback transaction mechanism like this?  Is there a race condition or other scenario that could leave the database in an inconsistent state?
3.  There are no POST requests accepted at this url/view, but since this page would not require login, could a malicious user take advantage of this view to screw up the database?

```python
class myModelDetailView(DetailView):
    queryset = MyModel.objects.all()

    def version_view(self, request, rev, *args, **kwargs):
       # step back "rev" number of revisions and render response
        versions = Version.objects.get_for_object(self.get_object())
        version = versions[min(versions.count() - 1, rev)]
        try:
            with transaction.atomic(using=version.db):
                # Revert the revision.
                version.revision.revert(delete=True)
                # Get the object and render the response
                self.object = self.get_object()
                context = self.get_context_data(object=self.object)
                response = self.render_to_response(context)
                response.render()  # eager rendering of response before db rollback
                raise _RollBackRevisionView(response)
        except _RollBackRevisionView as ex:
            return ex.response

    def get(self, request, *args, **kwargs):
        try:
            # look for rev parameter in get string
            rev = int(self.request.GET.get('rev', False))
        except Exception:
            rev = 0
        if rev > 0:
            return self.version_view(request, rev, *args, **kwargs)
        return super().get(request, *args, **kwargs)
```

**Comment by etianen** [comment]
These are good questions! I'm happy to help.

1. No. Until the transaction is committed, the data is not visible to other
users. This is something guaranteed by the database engine. There are
database settings that could allow this to happen (it's called a dirty
read, I think), but the defaults disallow it.

2. No. Reversion abuses transactions to preview revisions, but the database
is designed to handle this sort of behaviour. It's  hacky piece of code,
and it makes me feel silly for writing it, but it's also still the best
solution I know of to the problem.

3. No. Worse case, the code generates a bit of disk IO. I can't think of
how this could be abused.

Since you're interested in this, check out the postgresql docs:

https://www.postgresql.org/docs/10/static/transaction-iso.html

Postgresql is a fine piece of software.

**Comment by tlambert03** [comment]
That's great news. Thank you so much for your response and for the software!
