### ISSUE TITLE
how to use django-reversion for future possible versions of models

### ISSUE THREAD

**Issue by csisnett** [etianen/django-reversion#727]
Hi everyone,

I'm creating a website using the Rest Framework, it enables users to  modify or create new objects, kinda like Wikipedia where anyone can make edits but it has to go through a process to be accepted.

I understand the default behaviour is to save previous changes, but I'd like to use the library to keep track of possible future versions of my models. (Until they get approved by selected users) The thing is the default behaviour is that we have to make change to our model object to create a new version, I would instead like to create a new version and then if accepted by the selected users, apply the changes to the object.

My question is: how could I create versions of models without altering the original object?

I still haven't quite figure out the concept of revision blocks which is why I may be asking this question.

If you think there's a better alternative to my problem I'm open to suggestions and if you're curious this is my repository: https://github.com/csisnett/padres-backend

**Comment by etianen** [comment]
It's an interesting idea. The trick would be to subclass the admin so that,
when saving the model, you do the following:

   1. Start a transaction.
   2. Save the model as normal, creating a revision.
   3. Load the latest "approved" revision.
   4. Roll back the model to the latest approved revision.
   5. Commit the transaction.

The end result would be that a new revision is created, but the model has
not changed.

Then, to approve a new version, you:

   1. Load the revision you want to approve.
   2. Apply the revision to the database, thus updating the model to the
   approved version.

**Comment by csisnett** [comment]
Thanks for replying etianen, I'll be trying to code a solution based on what you told me. I will let you know when I did it or if I have further questions,

Carlos
