### ISSUE TITLE
Index for GenericForeignKey?

### ISSUE THREAD

**Issue by blueyed** [etianen/django-reversion#754]
In https://code.djangoproject.com/ticket/26964 I've read that django-reversion is missing an index for the GFK.

Code: https://github.com/etianen/django-reversion/blob/5ece8248eb146270edb89f42bb444ac3ac7c66d9/reversion/models.py#L224-L228

Do you think it makes sense to have it?
Might be related to https://github.com/etianen/django-reversion/issues/748 even, but have not investigated yet.

**Comment by etianen** [comment]
Not a bad shout.

If you can show a performance inprovement for some of the django-reversion
queries, I’m all for it!

**Comment by longhotsummer** [comment]
I was also concerned about this until I realised that `Version.objects.get_for_object` uses the compound index cleared on model, which ensures per-object version are efficient.

As a tip to anyone else, if you're fetching a lot of revisions but don't need their serialized data, use `defer('serialized_data')` to defer that field until you actually need it. This can make a big difference when your serialized objects are large, such as because they contain large documents.
