### ISSUE TITLE
Unclear on implications of intentionally not running createinitialrevisions...

### ISSUE THREAD

**Issue by djpretzel** [etianen/django-reversion#755]
The createinitialrevisions management command generates about 600MB worth of data that I'd rather avoid, in the interest of keeping the database in question leaner in general.

django-reversion seems to work just fine if the initial revisions aren't present, but the documentation in multiple spots says that the command **_should_** be run...

So my question is, _beyond_ not having the baseline revision to compare against, are there any other downsides to running without initial revisions? This still provides data for any new edits, as well as undelete functionality, and that's all I care about, and don't want the 600MB of redundant data if I can help it...

Assuming this is safe, I feel like the documentation should clarify the implications of operating in this fashion...

**Comment by etianen** [comment]
The downside is that, when you delete a model instance, it won't show up in
the "deleted revisions" view. At least one revision must exist for a model
instance before it'll be picked up by the "deleted revisions" page.

**Comment by djpretzel** [comment]
@etianen Indeed, the items I was testing with had all been edited at least once; when I attempted to delete and restore an _unedited_ item, I was unable.

Does that mean that if you prune your revision history, you could also end up in a situation where deletions cannot be recovered?

**I think undelete/recovering is potentially important enough that it shouldn't rely on an existing revision to function**; in other words, what about an option to create an initial revision, if one does not exist, on deletion?

`ENSURE_INITIAL_REVISION_ON_DELETE = True`

...or similar? So if an model is registered with reversion, on deletion there would first be a quick check to see if an initial revision existed, and one would be created first before deletion occurred.

This would have two benefits:

1. It would allow for the type of "day forward" configuration I'm attempting, where createinitialrevisions isn't run, while maintaining the benefit of recover/undelete.

2. It would prevent situations where users deleted their revision history and didn't understand why recover/undelete was no longer working.

...the second benefit in particular almost makes me think this should be default behavior; otherwise you have scenarios where undelete/recover capability is expected, but not available.

Thoughts?

**Comment by etianen** [comment]
If you prune the revision history, then you lose the ability to recover a
deletion, yes. You also lose the ability to rollback from the first save.
There is an option to the deleterevisions command called "keep" that allows
you to keep at least one revision per object, to prevent this happening.

I can see the advantage of creating an initial revision on delete. The
major downside being that it prevents the fast-path on bulk delete. This
means that bulk deletes can get very slow and memory intensive. I don't
think that this should be the default behavior, since the performance
regression can be considerable.

The combination of createinitialrevisions and deleterevisions --keep=1
works well for the majority of use-cases, I think. I'm not sure that adding
a pre-delete check adds much, given the performance regression.

**Comment by etianen** [comment]
You're not the first to request this feature, so I'd be open to a pull
request.

Rather than a global setting, it should be an argument to register(),
called lazy_initial. If True, it would in the post_save and pre_delete
handlers, check if a revision for that model exists, and create it if
necessary.

In the post_save, it should only do the lazy initial check if it is not a
creation.

There would be a race condition here, but the worse case is that a
duplicate initial revision is created, so it's not serious.

**Comment by MRigal** [comment]
The PR #774 might bring enough speed to not have to skip the creation anymore...
