### ISSUE TITLE
Migrations snafu

### ISSUE THREAD

**Issue by andreasnuesslein** [etianen/django-reversion#781]
Ahoy all,

I know this has been discussed a lot, but `migrations` are still somewhat messed up.
i.e.:
> 3.0.2 - 05/11/2018
> Removed squashed migrations, as they subtly messed up the Django migrations framework 
> (@etianen).

However: version 3.0.3 still has 
```
$ l migrations/
total 8.0K
-rw-r--r-- 1 nuts nuts 2.6K Mar 18 10:52 0001_squashed_0004_auto_20160611_1202.py
```

So is the squashed migration gone or not? :)
According to https://github.com/etianen/django-reversion/compare/v3.0.2..v3.0.3  nothing changed in that time.

Cheers

**Comment by andreasnuesslein** [comment]
Oh I think I get it now.
What remains is the one `squashed`-migration. Deleted are the migrations that have been replaced by the squashed one.
I was having trouble with this coming from an (very much) older version. Maybe it'd be good to write a few more words in the changelog explaining this?

Cheers

**Comment by etianen** [comment]
I've entirely lost track of which problems were caused by people not
updating django-reversion for 2 years, and which bugs were caused by
problems with the Django migration framework.

If someone can write something in the changelog to definitively tell people
how to migrate from (INSERT REVERSION VERSION WITH BEFORE THE SQUASH) to
(INSERT REVERSION VERSION AFTER THE SQUASH), I'd merge it in. I don't have
the energy to figure it all out from the start myself, I'm afraid!

**Comment by andreasnuesslein** [comment]
fair enough :)
