### ISSUE TITLE
ProtectedError

### ISSUE THREAD

**Issue by cfblaeb** [etianen/django-reversion#813]
Hi,

I have a model (my_model) with foreignkeys with "on_delete" set to "models.PROTECT".
my_link = models.ForeignKey(my_other_model, on_delete=models.PROTECT, null=True, blank=True)
If I create a my_model and dont set my_link, then reversion works fine.
But if I set my_link to actually link to an instance of my_other_model then I get the following error when I try to look at a reversion history instance in the admin view.
E.g going to:
http://127.0.0.1:8000/admin/my_app/my_model/1/history/1/
gives: 
Internal Server Error: /admin/my_app/organism/1/history/1/
Traceback (most recent call last):
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/reversion/admin.py", line 214, in revision_view
    return self._reversion_revisionform_view(
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/reversion/admin.py", line 164, in _reversion_revisionform_view
    version.revision.revert(delete=True)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/reversion/models.py", line 101, in revert
    collector.collect(list(group))
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/db/models/deletion.py", line 245, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/home/my_user/.pyenv/versions/3.8.0/envs/ve38/lib/python3.8/site-packages/django/db/models/deletion.py", line 23, in PROTECT
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'my_other_model' because they are referenced through a protected foreign key: 'my_model.mylink'", <QuerySet [<my_model: my_model_string>]>)
"GET /admin/my_app/organism/1/history/1/ HTTP/1.1" 500 121554

It would appear the offending part is when reversion tries to : "# Delete objects that are no longer in the current revision."

**Comment by etianen** [comment]
I'm not sure that django-reversion can do anything differently here.
Database integrity is preventing the rollback of the revision.

I guess it would be best to catch the error and give a nicer message to the
user.

**Comment by cfblaeb** [comment]
But thats the thing: I'm not doing a rollback. I'm merely looking at a previous version.
And secondly, if I understand the "models.PROTECT" setting correctly then the database should merely prevent a model instance from being deleted in situations where that instance is the target of a foreignkey from another model instance.
In other words, I should be able to roll back to any previous version of my model instance since I'm never deleting the instance.

**Comment by etianen** [comment]
In order to display the revision, django-reversion performs the rollback,
rendered the page, then aborts the transaction. So the rollback still has
to be performed in order to render the page.

If there's inline models in the admin page, then rolling back results in
inline models not present in the original revision being deleted. Does your
admin model contain inlines? I'm assuming that's where the PROTECTED error
is coming from.

**Comment by cfblaeb** [comment]
Heres a minimal example of a django project to demonstrate the bug: https://github.com/cfblaeb/reversion_bug_demo

It contains 1 app with 2 models.
The first model simply has a textfield.
The second model has  foreign key to the first model and its set to "on_delete=models.PROTECT"
I then create 2 instances of the first model and then 1 instance of the second model.
Originally the second model is set to link to instance 1 of the first model.
Then I change it to link to instance 2 of the first model.
Then in the admin interface, I look at the reversion history of the second model instance:
http://127.0.0.1:8000/admin/bug_app/mysecondmodel/1/history/
Now if I click the latest version, then everything is fine, but if I click the original version I get the "ProtectedError".

I hope that sufficiently explains how to reproduce the error.
I can understand from your explanation why the error occurs.
I do not know your code well enough to offer suggestions for how to solve the issue, but it seems performing a rollback is not going to work.

**Comment by etianen** [comment]
I've just pushed a commit to master that should give a better error message. Let me know what you think!

**Comment by DumData** [comment]
Well that's definitely a nicer way to display the error, but I don't it makes any difference in regards to clarity of the error, i.e. why am I getting this error and how do I fix it.

Also just to be clear: Are you saying that django-reversion will not track a foreignkey when on_delete is set to PROTECT? Because then I need to find another solution.

**Comment by etianen** [comment]
Unfortunately, I don't get any better information from Django than that.
Unless I'm going to parse the text of the error message and somehow
reformat it into a more palatable form, that's it.

Django reversion can track PROTECT foreign keys. However, it can't revert
the following case:

   - The model is registered with the admin, AND
   - The model has inlines, AND
   - The inline model is referenced by another model with a PROTECT foreign
   key, AND
   - The inline model does not exist in the previous revision

But nothing could revert this scenario, since you're asking the DB to roll
back to an inconsistent state. You can resolve this by changing the PROTECT
foreign key to CASCADE or SET_NULL. Alternatively, you accept that adding a
new inline model referenced by a PROTECT foreign key has the effect of
invalidating previous revisions for that model.

**Comment by keyvanm** [comment]
I'm running into this problem, and the issue is that the related object (FK) wasn't created during that revision. I don't understand why reverting to the previous version of the parent objects attempts to delete the related object totally, which causes other objects that have FK to the related object to also lose their relationship.

**Comment by etianen** [comment]
Consider this model setup:

``` py
class Parent(models.Model):
    pass

class Child(models.Model):
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE)

class Related(models.Model):
    child = models.ForeignKey(Child, on_delete=models.PROTECT)
```

`Parent` is registered with the Django admin, with `Child` as an inline.

Now do this:

Revision 1:
- Create a `Parent`

Revision 2:
- Update the `Parent`, and add a `Child`
- Create a `Related`, pointing at the `Child`.

Rolling back to Revision 1 requires deleting the `Child`, since it's not present in Revision 1. However, deleting the `Child` is impossible, since the `Related` has a protected foreign key to it. Since the revision cann't be rolled back, an error is raised.

**Comment by keyvanm** [comment]
@etianen The problem is that for me the `Child` instance is created way before Revision 1, so it existed even before the `Parent` instance existed. Yet it is still being deleted by reverting back to Revision 1.

**Comment by etianen** [comment]
Is the Child model present as an inline model in the admin? If so, you
should reconsider that. django-reversion assumes that child inlines are
"part of" the parent model, and will always be grouped in a revision with
them.

**Comment by DumData** [comment]
I see. That explains why I didn't understand the behaviour of django-reversion.
When I add the "child" inline to the "Related" admin model, I expect django-reversion to track changes to the fields of "Related". I do not expect it to delete or otherwise touch the "child" referred to by the foreignkey.

Could django reversion maybe have an option to just track the value of foreignkey rather than control the actual object linked to by the foreignkey?

**Comment by etianen** [comment]
You can customise the registration of models using the low-level API:

https://django-reversion.readthedocs.io/en/stable/api.html#registering-models

I think that, in your case, a simple @reversion.register() above both your
parent and child models would make things behave as expected.

However, be careful of having a model be available as both a top-level and
a child model in the admin. It'll confuse django-reversion, and most likely
confuse users too, as it means there's two ways of creating and updating a
given model instance.

**Comment by DumData** [comment]
Well I apologize. 
I thought I had tested simply not having the inline follow the foreignkey but apparently not well enough because that does exactly what I want.
Thanks.

**Comment by etianen** [comment]
Excellent! Glad it's working. :)

**Comment by keyvanm** [comment]
@etianen It is not an inline but a Foreign Key.

**Comment by keyvanm** [comment]
Hi, any word on this issue? I'm trying to figure out if my understanding is wrong or if this is an actual bug. 

In the above example a list of predefined `CompanyTypes` are created first (let's say `private` and `public`). Then each `Company` is associated with a type. 

If I change the `company_type` of a `Company` (let's say to `private`) and then try to revert back to a revision before this change, `CompanyType: private` gets queued for deletion, which triggers `ProtectedError`. 

Since this issue is closed, I can open another issue with more details upon your wish.

**Comment by etianen** [comment]
That does not sound right at all. Can you give me a minimal example I can
run?

**Comment by keyvanm** [comment]
For sure! 
Using ` django-reversion==3.0.5`

```python
class CompanyType(models.Model):
    name = models.CharField()

@reversion.register(follow=('company_type',))
class Company(models.Model):
    name = models.CharField()
    company_type = models.ForeignKey(CompanyType, on_delete=models.PROTECT)
```
```python
@admin.register(CompanyType)
class CompanyTypeAdmin(VersionAdmin):
    pass

@admin.register(Company)
class CompanyAdmin(VersionAdmin):
    pass
```

Create a couple `CompanyType` instances, e.g. type1 and type2. Then create a `Company` instance and set `company_type` to be type1. Then edit the instance and set `company_type` to be type2. Then try to revert it to the first revision.

**Comment by etianen** [comment]
Remove follow=("company_type",) , then it will work as expected.

The follow directive tells django-reversion to include the whole company
type model in the revision, not just the FK.

**Comment by keyvanm** [comment]
Thanks man! That seems to work. What are the appropriate use cases to use `follow`?

**Comment by etianen** [comment]
Use it when you consider the fields in the followed model "part" of the
originating model.

The inline models in the Django admin interface, for example, would
typically be considered part of the parent model.

It's definitely a confusing aspect of the lib. For most people who just use
the django admin integration, the defaults just work. Going under the hood
and using the low level API is definitely a lot harder to understand.
