### ISSUE TITLE
Add support for bulk creating revisions

### ISSUE THREAD

**Issue by bluesurfer** [etianen/django-reversion#815]
After a bulk operation on a bunch of objects I would like to efficiently create all the corresponding revisions.

Something like this:
```
books = Book.objects.all()
books.update(title=F('title') + 'foo')

reversion.bulk_create_revisions(
  objs=books,
  comment='Changed title'
  user=johndoe
)
```

**Comment by etianen** [comment]
At the moment, each revision, and each version, is saved with a call to
save(). In the case of your example, that would currently result in 2 db
calls per object (plus an additional DB call to load all the objects into
memory in order to save the version info). So in total, for 1000 objects,
this would be 2001 DB queries.

This could be optimized into three huge queries potentially (load objects,
bulk-create revisions, bulk-create versions). The downside would be that
the pre- and post-save signals for Version and Revision would not be sent,
which some people expect.

However, I suspect that the performance increase would not be great. An
update() call is typically made when a large number of objects are
involved, and it's not feasible to load them all into memory for individual
save() calls. Since reversion would have to load all the objects into
memory anyway in order to save the version information, this bulk operation
would necessarily involve a lot of memory allocations. Also, the actual
process of serializing revision information is quite slow and CPU
intensive, which would lessen the potential impact of the more efficient DB
operations.

So while there are potential efficiency gains to be had here, they would
come at the expense of potentially huge memory usage. Since people use
update() to avoid huge memory usage, I'm not sure this is worth pursuing.
