### ISSUE TITLE
Should model deletion signal be handled?

### ISSUE THREAD

**Issue by matthijskooijman** [etianen/django-reversion#830]
It seems that only model saving causes models to be added to a revision. However, in configurations with `follow`, I think that deletion should also trigger this, if the deleted model has `follow` set.

Consider the following models:

```
@reversion.register(follow=('address',))
class Person(models.Model):
    ... More fields ...

@reversion.register(follow=('person',))
class Address(models.Model):
	person = models.OneToOneField(Person, on_delete=models.CASCADE)
    ... More fields ...
```

The idea is that `Address` is just a "slave" of `Person`, it only has meaning as part of a `Person` (note that I used OneToOne in this example and it might been more sensible to just include the `Address` fields in `Person` directly , but the same thing applies to e.g. `ForeignKey` as well).

This approach works well: When I create an Address, or change an address, (in my application frontend, or through a `PersonAdmin` that has the `Address` as an inline) a revision is created that includes both models, so when looking at the `Person` history in the admin, I nicely get all changes.

However, when I now *delete* this address in my frontend, without touching the user, no revision is created, so this deletion (which is essentialy a *modification* of the `Person`) does not show up in the `Person` history.

To fix this, I think it would be sufficient to register a deletion signal handler that does something like:
```
def _post_delete_receiver(sender, instance, using, **kwargs):
    for follow_obj in _follow_relations(instance):
        add_to_revision(follow_obj, model_db=using)
```

Maybe the delete handler could also *remove* the deleted object from the revision (if already present). Doing so might allow simplifying `_create_revision` to skip checking for which objects still exist, and might also make the revisions more correct in the face of concurrency (I think a version might be omitted from a revision when it is deleted by another thread between saving the instance and saving the revision, but that might actually be harder to really fix properly). Anyway, this is really another issue, I guess.

**Comment by etianen** [comment]
Reversion did use to track delete signals, and it was removed because it caused all sorts of issues (left as an exercise for your to find all the issues in the tracker!).

But, in the case of this, I think you might have a very good point. When a deletion represents a *change* in another model, it makes sense to record all other models *except* the one that has just been deleted, as your code snippet suggests.

Possibly we can simplify the code for "checking for which objects still exist" by having the delete signal also remove the current object from the revision? I seem to remember some awkward edge case for the final "exists" check, but I can't remember what it might be.
