### ISSUE TITLE
Customized Set Comment 

### ISSUE THREAD

**Issue by nikolas310** [etianen/django-reversion#836]
In my model I've added like below. My ques is how can I set admin like comment. changed field1, field2 etc...

   ```
 def save(self, *args, **kwargs):
        with transaction.atomic(), reversion.create_revision():
            if self.id:
                if hasattr(self, 'updated_by'):
                    reversion.set_user(self.updated_by)
                reversion.set_comment("Updated")
            else:
                if hasattr(self, 'created_by'):
                    reversion.set_user(self.created_by)
                reversion.set_comment("Created")
            super().save(*args, **kwargs)
```

**Comment by etianen** [comment]
It's tricky to do what you want in a model's save() method. In order to know which fields have changed you would need to:
1. Load the "current" version of the model from the DB using `select_for_update` to protect against race conditions.
2. Iterate over the "current" fields, and the "new" fields, checking for differences, and building a comment.
