### ISSUE TITLE
Upgrading: Was the deletion of a consistent migration lineage a mistake or intentional?

### ISSUE THREAD

**Issue by oregon** [etianen/django-reversion#837]
It seems at first glance incredibly odd this project hamstrings itself by squashing migrations and providing no consistent path to possibly be upgraded across versions.  I read a handful of "migration" related topics in the Issue queue but couldn't find a clear answer to this.

Migrations for this project require custom hand-writing schema migrations somewhere via the SchemaEditor since the migrations don't carry lineage.  This seems like a very odd requisite and I have to believe, totally unnecessary.  Did Django thwart this projects versioning sanity that produced this result?  I haven't seen the problem in other packages prior, and since there are a handful of threads semi-related, I think this backstory would be helpful to the many users of django-reversion from Django's popular past.  Thanks.

**Comment by etianen** [comment]
Squashing the migrations was a mistake. I assumed that people would keep their django-reversion library relatively up to date. Turns out, people are still upgrading from versions that are years old.

Unfortunately, it's a mistake that cannot be undone, as adding the squashed migrations back in breaks anyone who's upgraded past v3.0.2.

The changelog includes a note about how to migrate past v3.0.2.

https://github.com/etianen/django-reversion/blob/master/CHANGELOG.rst#302---2018-11-05

You don't need to handle-write schema migrations, you just need to run a few console commands to do the upgrade in two phages.

**Comment by s4ke** [comment]
Thanks for clarifying this here and thanks for the how to. Saved some debugging time.
