### ISSUE TITLE
Adopt safe revision naming scheme

### ISSUE THREAD

**Issue by emorozov** [etianen/django-reversion#855]
After updating some minor dependency in our project (not django-reversion), I've found that our project suddenly failed to build.
Because we do not lock minor versions of dependencies in our pyproject.toml file, when I've upgraded some unrelated dependency, poetry also took liberty to upgrade django-reversion from 3.0.7 to 3.0.8. Which wouldn't be a huge issue normally, if 3.0.8 wouldn't break compatibility with Django 1.11.

It seems to me that such drastic changes should cause a change of the major version number. Inclusion of such big incompatible changes into a release that changes only patch version may cause a huge failures in a number of projects.

> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

(https://semver.org/#spec-item-6)

**Comment by etianen** [comment]
Probably. You could also argue that, since Django 1.11 became completely unsupported seven months ago, it's not really something package maintainers should worry about any more. Also, Django itself is also quite willing to break backwards compatibility on minor releases too.

The reality is that semantic versioning _just about_ protects you from breaking changes within a library, but when considering the interactions between libraries, it doesn't really work. It's a hint, and it's not even a universally-adopted hint in the Python ecosystem.

I understand your frustration. I spent about two hours yesterday trying to install a package using pipenv without _upgrading every package in my project at the same time_. It should be possible to upgrade a minor dependency without upsetting everything else. That's the real issue here.

Should I follow strict semver here and introduce a major version bump every time I drop support for a Django version? Should I follow Django's interpretation and use minor version bumps instead? Should I count unsupported Django versions in any of these decisions? Or should I just consider the API surface of django-reversion itself when determining the semver version bump? I don't think there's a 100% correct answer here.
