### ISSUE TITLE
Re-add support for `bulk_create`

### ISSUE THREAD

**Issue by dehnert** [etianen/django-reversion#924]
Between [1.8.0](https://django-reversion.readthedocs.io/en/stable/changelog.html#id50) and 1.8.6 (#380), reversion used `bulk_create` when creating versions, which presumably dramatically improved performance when creating a revision with many changed model instances[1]. It sounds like the motivation for removing this was inability to get back object primary keys from `bulk_create`, but that has since been fixed on some popular databases -- [Django 1.10](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#bulk-create) (released about a year and a half after #380) added some support (only PostgreSQL at the time). SQLite was added in [Django 4.0](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#bulk-create), and MariaDB was added sometime in the middle. It looks like there's a convenient feature test for this (`connection.features.can_return_rows_from_bulk_insert`), so it would be nice if django-reversion could use `bulk_create` when feasible.

(I found #380  while trying to figure out why tons of queries were being used despite the [changelog](https://django-reversion.readthedocs.io/en/stable/changelog.html#id50) claiming reversion uses bulk_create, so if you don't re-add `bulk_create` support it might be nice to note the change somewhere?)

[1] I haven't benchmarked this specifically, but a script that creates several thousand objects went from 30 minute runtime to ~3 minutes by doing far more query batching, so I suspect this is significant.

**Comment by spapas** [comment]
Hello friends, this would be really useful to me also. I've got some objects that I create through bulk_insert or update with bulk_update and I am forced to save them one-by-one to have proper revisions.

**Comment by etianen** [comment]
I'm a bit short on time at the moment, but I'd be happy to take a PR that implemented this.

**Comment by stianjensen** [comment]
> Hello friends, this would be really useful to me also. I've got some objects that I create through bulk_insert or update with bulk_update and I am forced to save them one-by-one to have proper revisions.

So this, specifically, is another problem than what's described in this issue! A workaround for your problem is explained here:
https://github.com/etianen/django-reversion/issues/925

Essentially, if you use bulk_create or bulk_update to update a lot of models in one query, also iterate over the objects and call `add_to_revision` on them (that does not by itself cause one immediate db query per model). Then, until _this_ issue gets fixed, that will cause n queries upon save to create the n versions, but hopefully in the future, with a fix for this issue, that saving of the n versions will also itself be performed via only one bulk query (plus one extra query to save the Revision model instance).
