### ISSUE TITLE
Add step to show version data and allow for confirmation prior to to reversion

### ISSUE THREAD

**Issue by tysonclugg** [etianen/django-reversion#929]
When reversion has been configured for the admin, the history view of an object shows the following:
![image](https://user-images.githubusercontent.com/218251/204175173-fc2b4e09-b898-4e7a-a261-d9b069b417b9.png)

The issue is that clicking on any of the linked versions immediately results in an attempt at reverting to that version.  Regardless of any wording placed around the links, the linked pages are retrieved using HTTP GET and result in an "unsafe" operation, resulting in a violation of the HTTP spec:
> [If the purpose of such a resource is to perform an unsafe action, then the resource owner **_MUST_** disable or disallow that action when it is accessed using a safe request method.](https://httpwg.org/specs/rfc9110.html#safe.methods:~:text=If%20the%20purpose%20of%20such%20a%20resource%20is%20to%20perform%20an%20unsafe%20action%2C%20then%20the%20resource%20owner%20MUST%20disable%20or%20disallow%20that%20action%20when%20it%20is%20accessed%20using%20a%20safe%20request%20method.)

Note use of the word MUST in the wording above (emphasis mine) - this is an [absolute requirement](https://www.ietf.org/rfc/rfc2119.txt#:~:text=1.%20MUST%20%20%20This%20word%2C%20or%20the%20terms%20%22REQUIRED%22%20or%20%22SHALL%22%2C%20mean%20that%20the%0A%20%20%20definition%20is%20an%20absolute%20requirement%20of%20the%20specification.) and a strict violation of expected web semantics.

The fix seems relatively easy. Show an intermediary page (like Django does when deleting an object), asking the user to confirm their action which should then POST a request that performs the reversion returning a HTTP 301 response the `Location` header set to either the object history or change page.

**Comment by etianen** [comment]
Clicking on the link does not revert the version... it shows a preview of the revert, but does not actually perform the revert. The revert is performed when the user clicks "save".

The _implementation_ is that a revert is performed, then the transaction is rolled back. This should undo any effect of rendering the reverted version.

In what was is this unsafe and a violation of HTTP semantics?

**Comment by tysonclugg** [comment]
From the stack trace that we captured, it appears that revert was called from the revision view and it attempted to delete some of our User instances.
![image](https://user-images.githubusercontent.com/218251/204395128-5d852255-e55b-420a-846b-8298b6f786a7.png)
![image](https://user-images.githubusercontent.com/218251/204395394-39f7bb4f-5c66-4c56-9587-2559f245beb4.png)

**Comment by tysonclugg** [comment]
> The _implementation_ is that a revert is performed, then the transaction is rolled back. This should undo any effect of rendering the reverted version.

That's an interesting idea, but based on the assumption that there is transaction support in the DB engine being used.  There are notes in the Django docs about how [particular MySQL configurations don't support transactions](https://docs.djangoproject.com/en/4.1/topics/db/transactions/#transactions-in-mysql).

I'm well aware that #813 has bitten us here and that we're on an older version of django-reversion (3.0.4), but it's still a bad idea to call delete and then assume that a transaction rollback will leave everything in a pristine state.  There are other issues that could most certainly bite depending on configuration, such as having the transaction isolation level set to allow dirty reads resulting in 404's as objects disappear momentarily before the rollback kicks in.

My point is you can't know how this behaviour will affect any given application, and you should avoid calls that modify the database in a view that isn't meant to modify the database.

**Comment by way-dave** [comment]
Right at the top of the [admin integration](https://django-reversion.readthedocs.io/en/stable/admin.html#admin-integration) page, it says:

> The admin integration requires that your database engine supports transactions. This is the case for PostgreSQL, SQLite and MySQL InnoDB. If you are using MySQL MyISAM, upgrade your database tables to InnoDB!

The semantics of a database transaction are that rolling it back will leave the database exactly as if the transaction has not occured. So from the point of view of the database, it is absolutely fine to assume that a mutating operation, followed by a rollback, leaves the app in a pristine state. The same is true of Django's file storage abstractions.

Other side-effects in other datastores (e.g. redis, queues) triggered by a model save might break this assumption, of course. And that's where the danger is.

But the _intention_ of the revert preview is that it's safe, non-mutating view, and for models that use only the database and file storage abstractions, it is absolutely safe and non-mutating. Just because a user can customize a model to make this not the case by doing some funny business in `save()`, doesn't make this inherantly unsafe or unsemantic.

Semantically, the revert preview view is supposed to be safe and stateless, so it should be a GET request. And it's implementation for most models is absolutely safe and stateless. Making this a POST request would be unsemantic, as it would imply the view _is intended_ to be mutating.

Instead, I would take the view that the documentation should call out the additional requirements for a model to be used in the admin integration to avoid breaking this assumption.
