### ISSUE TITLE
Manytomany Field not deleted or recreate

### ISSUE THREAD

**Issue by bast-ii** [etianen/django-reversion#930]
Hey,

i have the following models

`persons/models.py`:

```
class Person(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, verbose_name="Name")
    categories = models.ManyToManyField('categories.Category', through='categories.CategoryPerson', verbose_name="Category", blank=True)

    class Meta:
        verbose_name = "Person"
        verbose_name_plural = "Persons"

    def __str__(self):
        return '%s' % self.name
```

And the `categories/models.py`:

```
class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, verbose_name="Name")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class RiskSeverity(models.Model):
    risk_s = models.PositiveSmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(4)])

    class Meta:
        abstract = True


class RiskProbabilityOccurrence(models.Model):
    risk_p = models.PositiveSmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(4)])

    class Meta:
        abstract = True


class CategoryPerson(RiskSeverity, RiskProbabilityOccurrence):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="Category")
    person = models.ForeignKey('persons.Person', on_delete=models.CASCADE, verbose_name="Person")

    class Meta:
        unique_together = ['category', 'person']

```

I have create a person instance and add CategoryPerson (we name it "ABC") to that.
Then i add another CategoryPerson to the person instance and change the name of the person and the `risk_s` and `risk_p` fields from the "ABC" CategoryPerson.

If i revert to the first version, the name of the person and the `risk_s` and `risk_p` fields of the "ABC" CategoryPerson are reverted. But the other CategoryPerson not deleted. Why?
The same is when i delete a CategoryPerson and revert to a older version. Then the CategoryPerson is not recreated.

I have register the models in the admin.py:

```
class PersonAdmin(VersionAdmin):
    def reversion_register(self, model, **options):
        options["follow"] = ("categories",)
        super().reversion_register(model, **options)


admin.site.register(Person, PersonAdmin)


class CategoryAdmin(VersionAdmin):
    pass


admin.site.register(Category, CategoryAdmin)


class CategoryPersonAdmin(VersionAdmin):
    def reversion_register(self, model, **options):
        options["follow"] = ("category", "person",)
        super().reversion_register(model, **options)


admin.site.register(CategoryPerson, CategoryPersonAdmin)

```

**Comment by bast-ii** [comment]
Is it not possible?

**Comment by etianen** [comment]
Sorry for the delay in getting back to you, there's a lot going on in my life right now! :sweat_smile: 

There are a few things in your setup that look problematic to me:

First, you're using an M2M field with a through model. You need to [handle these very carefully in the django admin using inline models](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#working-with-many-to-many-intermediary-models). You don't seem to be doing that here, so it's unclear how the admin will be handling that. I'd imagine some suprising things would happen.

You also don't have a clear ownership of the data in your admin definitions. Really, a given model, and all it's `follow` relations, should be in a single admin class, so that a save or revert of that admin view will clearly apply to a discrete set of models, and that view will be the only way of editing those models.

I'd refactor your code to avoid the M2M through approach entirely. I'd remove the `categories` M2M field from `Person`, and then do something like:

```
class CategoryPersonInline(admin.TabularInline):
    model = CategoryPerson


class PersonAdmin(VersionAdmin):
    inlines = (CategoryPersonInline,)

admin.site.register(Person, PersonAdmin)


class CategoryAdmin(VersionAdmin):
    pass


admin.site.register(Category, CategoryAdmin)
```
